name: MyFirstWorkflow
on: 
  push:
    branches: 
      - main

  
jobs: 
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List Files in repo
        run:  |
         echo "The repository ${{ github.repository }} contains the following
         files:"
         tree
